# 예외 (Exception)
## 1. 예외란
- 프로그램의 **실행 도중에 발생하는 ** 예상치 못한 **오류**
- 컴파일 시 발생하는 문법적인 에러는 예외 x
  - 나눗셈 시 나누는 수로 0이 입력
  - 나이 입력 시 0보다 작은 값 입력 등

- 처리되지 않은 예외는 프로그램의 실행 중단 원인
- 에러
  - 컴파일 에러(compile error)
  - 실행 에러(Runtime error) : 프로그램 실행 도중 발생되는 에러
    - 에러(error) : 메모리부족, 스택오버플로우 등 발생하면 복수할 수 없는 심각한 에러
    - 예외(exception) : 발생하더라도 수습될 수 있는 비교적 덜 심각한 오류

## 2. 예외처리
- 예외의 발생에 대비한 코드를 작성하는 것
- 프로그램 실행 도중 발생한 에러를 처리, 에러에 의해서 비정상적으로 프로그램이 종료되는 것을 막아줌
- 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것   

## 3. try~catch

```java
try{
  예외가 발생할 만한 코드들 배치
}catch(Exception e){
  예외를 잡아 실패에 대한 처리를 하는 코드
}
```

- 예외처리 없을 시   
```java
import java.util.Scanner;

public class Test1 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("두개의 정수 입력");
		int n1 = sc.nextInt();
		int n2 = sc.nextInt(); 
    //몫에 0 또는 문자를 넣으면 다음 구문까지 가지 못하고 실행에러 발생, 프로그램 종료됨
		
		System.out.println("목:"+n1/n2);
		System.out.println("나머지:"+n1%n2);
		
		System.out.println("\n----next----");
	}
}
```
- 예외처리 사용   
```java
import java.util.Scanner;

public class TryTest1 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		try {
			System.out.println("두개의 정수 입력");
			int n1 = sc.nextInt();
			int n2 = sc.nextInt();
			int result = n1/n2;
			
			System.out.println("목:"+result);
			System.out.println("나머지:"+n1%n2);
		}catch (Exception e) {
			System.out.println("예외 발생"+e.getMessage()); //예외 발생/ 발생이유 출력
		}//몫에 0 또는 문자를 넣어도 프로그램이 종료되지 않는다
		
		System.out.println("\n----next----");
	}
}
```
- 자바 가상머신이 예외상황 인식
- ArithmeticException 클래스의 인스턴스 생성
- 가상머신에 의해 생성된 인스턴스의 챔조값을 catch영역 매개변수에 전달 (Exception e)
- e.getMessage()
  - 매개변수의 참조변수를 이용, 예외상황 발생이유를 담은 문자열을 반환   

- for문에서 예외처리 이용   

```java
import java.util.*;
public class TryTest2 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		
		for(int i = 0; i<2; i++) {
			try {
				System.out.println("두 정수 입력");
				int n1 = sc.nextInt();
				int n2 = sc.nextInt();
				
				System.out.println("나눗셈:"+n1/n2);
			}catch(ArithmeticException e) {
				System.out.println("예외 : "+e.getMessage());
			}
		}
	}
} //예외가 발생해도 for문은 계속 돈다.
```
